[package]
name = "kittyaudio"
description = "An audio playback library focusing on simplicity"
license = "MIT OR BSL-1.0"
version = "0.1.0"
exclude = ["assets/**"]
documentation = "https://docs.rs/kittyaudio"
homepage = "https://github.com/zeozeozeo/kittyaudio"
repository = "https://github.com/zeozeozeo/kittyaudio"
keywords = ["audio", "playback", "gamedev"]
categories = ["multimedia"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
log = "0.4.20"
symphonia = { version = "0.5.3", features = ["all"], optional = true }
thiserror = "1.0.50"

[features]
default = ["use-symphonia"]
use-symphonia = ["symphonia"]
